spring:
  application:
    name: distributed-scheduling
  datasource:
    url: jdbc:mysql://localhost:3306/distributed_scheduling
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        #        generate_statistics: true
        #format_sql: true
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true

  flyway:
    enabled: false
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    schemas: distributed_scheduling
    url: ${spring.datasource.url}
    locations: classpath:/db/migration
    baselineOnMigrate: true
