spring:
  application:
    name: distributed-scheduling
  datasource:
    url: jdbc:mysql://localhost:3306/distributed_scheduling
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
